name: CI
on:
  push:

jobs:
  job-1:
    name: List workflows
    runs-on: ubuntu-latest
    steps:
      - name: List GH context
        env: 
          ACTIONS_STEP_DEBUG: true
        run: |
          uname



