name: node CI
on: push
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install
        run: npm install
      
      - name: Build
        run: npm build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with: 
          name: node_artifacts
          path: build.log

  test:
    runs-on: ubuntu:latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install
        run: npm install
      
      - uses: actions/download-artifact@main
        with:
          name: node_artifacts

      - name: Install
        run: npm install
      
