name: test-job
on:
  schedule:
    - cron: '*/5 * * * *'   
jobs:
  basic:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List envs
        run: env | grep GITHUB
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Short SHA 
        run: echo ${{ steps.vars.outputs.sha_short }}
          

      
