name: CI

on:
 push:


jobs:
  job_1: 
    runs-on: ubuntu-latest
    steps:
    - name: Set the value in bash
      env:
        GH: ${{ toJSON(github) }}
      run: |
        echo $GH
  job_2:
    uses: ./.github/workflows/reuse.yml


