name: Multiline env

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Add step summery
      id: step_one
      run: |
        echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

