name: CD
on: push
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy 
      run: |
        echo "Deployed"
        exit 1

    - name: Notify
      # if: failure()
      run:  echo "Notification sent"
          

      
