name: CI
on: push
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Masking the env
        run: |
          UUID=`uuidgen`
          echo "::add-mask::$UUID"
          echo "UUID=$UUID" >>$GITHUB_ENV
          
      - name: Validate
        run: |
          echo $UUID 