name: test-job
on:
  push:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run only on main 
        if: ${{ github.ref == 'refs/heads/main'}}
        run:
          echo $GITHUB_REF
          

      
