name: CD
on: push
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy 
      run: |
        exit 0

  notify:
    needs: prod-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Notify 
      env:
        NEEDS: ${{ toJson(runner)}}
      run: |
        echo hi
          

      
