name: CI
on:
  push:
jobs:
  create-table:
    runs-on: ubuntu-latest
    container: alpine/psql
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tables
        run: |
          PGPASSWORD=postgres psql -h postgres -p 5432 -U postgres -f script.sql

      - name: Validate
        run: |
          uname -a
          PGPASSWORD=postgres psql -h postgres -p 5432 -U postgres -d storedb -c "\dt"