name: CI

on:
  push:

jobs:
  job_1: 
    if: contains(github.ref, 'fix')
    runs-on: ubuntu-latest
    steps:
    - name: Set the value in bash
      run: |
        echo "### Hello world! :rocket:" 


