name: CI
on:
  push:

jobs:
  job-1:
    name: List workflows
    runs-on: ubuntu-latest
    steps:
      - name: List workflows
        run: |
          curl -H "Authorization: Bearer ${{ secrets.PAT }}"  https://api.github.com/repos/${{ github.owner }}/${{github.repository }}/actions/workflows


