name: Multiline env

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Set the value in bash
      id: step_one
      run: |
        {
          echo 'JSON_RESPONSE<<EOF'
          This is a 
          multine
          env
          echo EOF
        } >> "$GITHUB_ENV"
    
    - name: debug
      run: |
        echo $JSON_RESPONSE

