name: CI
on:
  push:

jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Request for approval
        run: |
          sleep 15

  job-2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Request for approval
        run: |
          sle3p 10
          

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: job-2
    if: ${{ ! success() }}
    steps:
      - name: Request for approval
        run: |
          echo notify