name: CI
on:
  push:

jobs:
  job-1:
    name: List workflows
    runs-on: ubuntu-latest
    steps:
      - name: List workflows
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN"  https://api.github.com/repos/{owner}/{repo}/actions/workflows


