name: Service container 2
on:
  push:
jobs:
  create-table:
    runs-on: ubuntu-latest
    container: alpine/psql
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: Install psql client
      #   run: |
      #     sudo apt-get update && sudo apt-get install postgresql-client
      #     psql --version