name: CI
on: push
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: workflow commands logging messages
        run: |
          echo "::group::Console logs"
          echo "somelog..."
          echo "somelog..."
          echo "::endgroup::"

