name: CI

on:
 pull_request:
 push:


jobs:
  job_1: 
    runs-on: ubuntu-latest
    steps:
    - name: Set the value in bash
      env:
        GH: toJSON(github)
      run: |
        echo ${{ env.GH }}


