name: CD
on: push
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy 
      run: |
        exit 1

  notify:
    needs: prod-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Notify 
      env:
        NEEDS: ${{ toJson(job)}}
      run: |
        echo $NEEDS
          

      
