name: CD
on: push
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' }} 
    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Dump GitHub context
      run:  env | grep GITHUB
          

      
