name: CD
on: push
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.repository.has_issues == true }} 
    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
          

      
