name: CD
on: push
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy 
      run: |
        exit 1

    - name: Notify
      if: ${{ ! success() }}
      run:  echo "Notification sent"
          

      
