name: CI
on: push
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Workflow commands
        run: |
          echo "::workflow-command parameter1={data},parameter2={data}::{command value}"
