name: CI
on:
  push:

jobs:
  clean-up:
    name: Mark issues stale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1
        with:
          days-before-stale: 7
          repository: ${{ github.repository }}
          

