name: CD
on: push
env:
  ISSUES: ${{ github.repository.has_issues}}
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    if: ${{ env.ISSUES == 'true' }} 
    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Dump GitHub context
      run:  env | grep GITHUB
          

      
