name: Context testing
on: push
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    if: ${{github.ref == '/refs/heads/main'}} && ${{github.repository.open_issues_count == 0 }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
          

      
