name: CI
on: push
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Masking the env
        id: set-secret
        run: |
          UUID=`uuidgen`
          echo "::add-mask::$UUID"
          echo "UUID=$UUID" >>$GITHUB_OUTPUT

      - name: Validate the secret
        run: |
          echo ${{ steps.set-secret.outputs.UUID }}