name: CI
on:
  push:

jobs:
  clean-up:
    name: Mark issues stale
    runs-on: ubuntu-latest
    steps:
      - name: Request for approval
        requires:
          - approval
          

