name: test-job
on:
  push:

jobs:
  big-fix:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, '/refs/heads/bugfix/*')}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

          

      
