name: Generate and Pass Secret Between Jobs

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate a secret (for demonstration purposes)
        id: generate_secret
        run: |
          # Example of generating a secret (you can generate any secret here)
          SECRET=$(echo "my_generated_secret_$(date +%s)")
          echo "Generated secret: $SECRET"
          # Set the generated secret as an output
          echo "my_generated_secret=$SECRET" >>GITHUB_OUTPUTS
    outputs:
      SECRET: ${{ steps.generate_secret.outputs.my_generated_secret }}    

  job_2:
    runs-on: ubuntu-latest
    needs: job_1  # This job depends on job_1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use the generated secret from job_1
        run: |
          echo "The secret passed from job_1 is: ${{ needs.job_1.outputs.SECRET }}"
