name: CI
on: push
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: workflow commands logging messages
        run: |
          echo "::debug::This is a debug message"
          echo "This is an info message"
          echo "::error::This is an error message"
          echo "::warning::This is a warning message"  

      - name: Workflow command testing
        run: |
          echo "::error file=app.js,line=10,col=15::Something went wrong"
