name: workflow-run
on:
  workflow_run:
    workflows: main-workflow
    types:
      - completed
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Some test
        env:
          CC: ${{ toJSON(github.event.workflow_run.conclusion) }}
        run: | 
          echo $CC